# Generated by Django 2.0.3 on 2018-03-07 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountingManager',
        ),
        migrations.DeleteModel(
            name='ProductManager',
        ),
    ]
