# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-26 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Analog', 'Analog'), ('Digital', 'Digital'), ('Smart', 'Smart')], default='Analog', max_length=7),
            preserve_default=False,
        ),
    ]
