# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-08 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_auto_20180307_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='prodlist',
        ),
        migrations.AddField(
            model_name='transaction',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Product'),
        ),
    ]
