# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-02 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='initialstock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='prodname',
            field=models.CharField(max_length=40),
        ),
    ]
