# Generated by Django 2.0.2 on 2018-03-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_transaction_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(max_length=20, unique=True)),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
                ('temporary', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Accounting Managers',
            },
        ),
        migrations.CreateModel(
            name='ProductManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(max_length=20, unique=True)),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
                ('temporary', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Product Managers',
            },
        ),
    ]
