# Generated by Django 2.0.2 on 2018-03-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_auto_20180302_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Admins',
            },
        ),
        migrations.AddField(
            model_name='accountingmanager',
            name='temporary',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productmanager',
            name='temporary',
            field=models.BooleanField(default=True),
        ),
    ]
