# Generated by Django 2.0.2 on 2018-03-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_auto_20180306_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingmanager',
            name='first',
            field=models.CharField(default='sample', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountingmanager',
            name='last',
            field=models.CharField(default='sample', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmanager',
            name='first',
            field=models.CharField(default='sample', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmanager',
            name='last',
            field=models.CharField(default='sample', max_length=20),
            preserve_default=False,
        ),
    ]
