# Generated by Django 2.0.2 on 2018-03-12 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_accountingmanager_productmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountingManager',
        ),
        migrations.DeleteModel(
            name='ProductManager',
        ),
    ]
