# Generated by Django 2.0.2 on 2018-03-06 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_auto_20180307_0145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountingmanager',
            name='first',
        ),
        migrations.RemoveField(
            model_name='accountingmanager',
            name='last',
        ),
        migrations.RemoveField(
            model_name='productmanager',
            name='first',
        ),
        migrations.RemoveField(
            model_name='productmanager',
            name='last',
        ),
    ]
