# Generated by Django 2.0.2 on 2018-04-19 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_auto_20180314_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='staticfiles/product_images/'),
        ),
    ]
