# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-19 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_auto_20180419_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='ecommerce/static/product_images/'),
        ),
    ]
